Repository leo-paz/grad-admissions-hub, pull requests merged in 2021-03, with the labels that each got.

#14 Enabling Cors for Apollo Client 😥
  backend/service/src/main/java/com/gradadmissionshub/service/Handler.java
Labels: needed for milestone

#17 Milestone 1 Complete
  backend/service/src/main/java/com/gradadmissionshub/service/Handler.java
  frontend/grad-admissions-hub-app/package-lock.json
  frontend/grad-admissions-hub-app/package.json
  frontend/grad-admissions-hub-app/src/App.js
  frontend/grad-admissions-hub-app/src/Components/GetBook1.js
  frontend/grad-admissions-hub-app/src/GraphQL/Queries.js
  frontend/grad-admissions-hub-app/src/Pages/Home.js
  frontend/grad-admissions-hub-app/src/index.js
  package-lock.json
Labels: needed for milestone

#19 Fetch graphql data
  frontend/grad-admissions-hub-app/src/readme.md
Labels: documentation

#23 Creating & Querying of Applicants and Professors⛓️
  backend/service/build.gradle
  backend/service/serverless.yml
  backend/service/src/main/java/com/gradadmissionshub/database/entity/Applicant.java
  backend/service/src/main/java/com/gradadmissionshub/database/entity/Professor.java
  backend/service/src/main/java/com/gradadmissionshub/database/repository/AbstractRepository.java
  backend/service/src/main/java/com/gradadmissionshub/database/repository/ApplicantRepository.java
  backend/service/src/main/java/com/gradadmissionshub/database/repository/ProfessorRepository.java
  backend/service/src/main/java/com/gradadmissionshub/service/GraphQLDataFetchers.java
  backend/service/src/main/java/com/gradadmissionshub/service/GraphQLProvider.java
  backend/service/src/main/java/com/gradadmissionshub/service/Handler.java
  backend/service/src/main/resources/schema.graphqls
Labels: needed for milestone

#25 Able to Create and Query all Entities
  backend/service/src/main/java/com/gradadmissionshub/database/entity/Applicant.java
  backend/service/src/main/java/com/gradadmissionshub/database/entity/Application.java
  backend/service/src/main/java/com/gradadmissionshub/database/entity/Professor.java
  backend/service/src/main/java/com/gradadmissionshub/database/entity/Review.java
  backend/service/src/main/java/com/gradadmissionshub/database/repository/ApplicationRepository.java
  backend/service/src/main/java/com/gradadmissionshub/database/repository/ReviewRepository.java
  backend/service/src/main/java/com/gradadmissionshub/service/GraphQLDataFetchers.java
  backend/service/src/main/java/com/gradadmissionshub/service/GraphQLProvider.java
  backend/service/src/main/java/com/gradadmissionshub/service/Handler.java
  backend/service/src/main/java/com/gradadmissionshub/service/helpers/ParsingCreateRequests.java
  backend/service/src/main/resources/schema.graphqls
Labels: needed for milestone

#38 Ui TouchUps and General Sign In Page
  frontend/grad-admissions-hub-app/package-lock.json
  frontend/grad-admissions-hub-app/package.json
  frontend/grad-admissions-hub-app/public/professor.jpg
  frontend/grad-admissions-hub-app/public/students.jpg
  frontend/grad-admissions-hub-app/src/App.css
  frontend/grad-admissions-hub-app/src/App.js
  frontend/grad-admissions-hub-app/src/Components/Navbar/Navbar.js
  frontend/grad-admissions-hub-app/src/Components/SignUpLogIn/SignUp.js
  frontend/grad-admissions-hub-app/src/Pages/Profile.js
  frontend/grad-admissions-hub-app/src/animations/applications.json
  frontend/grad-admissions-hub-app/src/animations/document.json
  frontend/grad-admissions-hub-app/src/animations/go-arrow.json
  frontend/grad-admissions-hub-app/src/animations/grad-student.json
  frontend/grad-admissions-hub-app/src/animations/home.json
  frontend/grad-admissions-hub-app/src/animations/profile.json
  frontend/grad-admissions-hub-app/src/animations/radio-button.json
  frontend/grad-admissions-hub-app/src/animations/review-star.json
  frontend/grad-admissions-hub-app/src/animations/settings.json
  frontend/grad-admissions-hub-app/src/icons/grad-hat.svg
Labels: enhancement
